#!/usr/bin/env python3

'''
   @file
   @ingroup <<<GROUP>>>
   @brief   <<<BRIEF>>>

            This code is Autogenerated from '<<<PYIFGENNAME>>>' with the MIT License.
            As such, please only hand-code within 'USER' tags.

   @author  <<<AUTHOR>>>
'''

from enum import Enum, unique, auto
# {{{USER_IMPORT}}}
# {{{USER_IMPORT}}}

<<<NESTED_NAMESPACE_BEGIN>>>

<<<CLASS_DOCUMENTATION>>>
@unique
class <<<CLASSNAME>>>(Enum):
    <<<ENUM_EXPAND>>>

<<<NESTED_NAMESPACE_END>>>