#!/usr/bin/env python3

'''
   @file
   @ingroup <<<GROUP>>>
   @brief   <<<BRIEF>>>

            This code is Autogenerated from '<<<PYIFGENNAME>>>' with the MIT License.
            As such, please only hand-code within 'USER' tags.

   @author  <<<AUTHOR>>>
'''
from abc import *

<<<NOT_FORWARD_DECLARABLE_HEADER_INCLUDES>>>
<<<FORWARD_DECLARABLE_HEADER_INCLUDES>>>

# {{{USER_HEADER_INCLUDES}}}
# {{{USER_HEADER_INCLUDES}}}

<<<NESTED_NAMESPACE_BEGIN>>>

    # {{{USER_LOCALS}}}
    # {{{USER_LOCALS}}}

    <<<CLASS_DOCUMENTATION>>>
    class <<<CLASSNAME>>><<<CLASS_INHERITENCE_HIERARCHY>>>
        <<<PUBLIC_OPERATIONS_DECLARE>>>
        # {{{USER_PUBLIC}}}
        # {{{USER_PUBLIC}}}
        <<<PROTECTED_OPERATIONS_DECLARE>>>
        # {{{USER_PROTECTED}}}
        # {{{USER_PROTECTED}}}
        <<<PRIVATE_OPERATIONS_DECLARE>>>
        # {{{USER_PRIVATE}}}
        # {{{USER_PRIVATE}}}

<<<NESTED_NAMESPACE_END>>>