/**
 * @file
 * @ingroup <<<GROUP>>>
 * @brief   <<<BRIEF>>>
 *
 *          This code is Autogenerated from '<<<PYIFGENNAME>>>.py' with the MIT License.
 *          As such, please only hand-code within 'USER' tags.
 *
 * @author  <<<AUTHOR>>>
 */

#ifndef <<<CLASSNAME>>>_HPP
#define <<<CLASSNAME>>>_HPP

#include "allplatforms/basetypes.h"
#include "Protocol.h"

// {{{USER_INCLUDES}}}
// {{{USER_INCLUDES}}}

#if defined(_MSC_VER)
#define __attribute__(x)
#pragma pack(push,1)
#elif defined(__GNUC__)
#elif defined(__clang__)
#endif  // #if defined(_MSC_VER)

namespace <<<NAMESPACE>>>
{

    // {{{USER_TYPES}}}
    // {{{USER_TYPES}}}

    /******************************************************
     * @brief Enumeration definitions
     ******************************************************/
    <<<ENUMS>>>

    /******************************************************
     * @brief Struct definitions
     ******************************************************/

    <<<PER_STRUCT_BEGIN>>>
    struct <<<STRUCTNAME>>>
    {
    <<<MEMBERSDECLARE>>>
    };
    <<<PER_STRUCT_END>>>

    /******************************************************
     * @brief Message definitions
     ******************************************************/

    <<<PER_MSG_BEGIN>>>
    struct <<<MSGNAME>>>
    {
    <<<MEMBERSDECLARE>>>
    };
    <<<PER_MSG_END>>>

    /******************************************************
     * @brief Message Payload Factories
     ******************************************************/

    <<<PER_STRUCT_BEGIN>>>
    <<<STRUCTNAME>>> Create<<<STRUCTNAME>>>(<<<SIGNATUREWITHDEFAULTS>>>);
    <<<PER_STRUCT_END>>>

     /******************************************************
     * @brief Message factories
     ******************************************************/

    <<<PER_MSG_BEGIN>>>
    <<<MSGNAME>>> Create<<<MSGNAME>>>(<<<SIGNATUREWITHDEFAULTS>>>);
    <<<PER_MSG_END>>>

} // namespace <<<NAMESPACE>>>

#if defined(_MSC_VER)
#pragma pack(pop)
#elif defined(__GNUC__) || defined(__clang__)
#endif // #if defined(_MSC_VER)

#endif // #ifndef <<<CLASSNAME>>>_HPP
