/**
 * @file
 * @ingroup <<<GROUP>>>
 * @brief   <<<BRIEF>>>
 *
 *          This code is Autogenerated from '<<<PYIFGENNAME>>>' with the MIT License.
 *          As such, please only hand-code within 'USER' tags.
 *
 * @author  <<<AUTHOR>>>
 */
#pragma once

<<<NOT_FORWARD_DECLARABLE_HEADER_INCLUDES>>>

/// {{{USER_HEADER_INCLUDES}}}
/// {{{USER_HEADER_INCLUDES}}}

<<<FORWARD_DECLARATIONS>>>

/// {{{USER_FORWARD_DECLARATIONS}}}
/// {{{USER_FORWARD_DECLARATIONS}}}

<<<NESTED_NAMESPACE_BEGIN>>>

    /// {{{USER_LOCALS}}}
    /// {{{USER_LOCALS}}}

    <<<CLASS_DOCUMENTATION>>>
    class <<<CLASSNAME>>><<<CLASS_INHERITENCE_HIERARCHY>>>
    {
    public:
        virtual ~<<<CLASSNAME>>>() {}
        <<<PUBLIC_OPERATIONS_DECLARE>>>
        /// {{{USER_PUBLIC}}}
        /// {{{USER_PUBLIC}}}
    protected:
        <<<PROTECTED_OPERATIONS_DECLARE>>>
        /// {{{USER_PROTECTED}}}
        /// {{{USER_PROTECTED}}}
    private:
        <<<PRIVATE_OPERATIONS_DECLARE>>>
        /// {{{USER_PRIVATE}}}
        /// {{{USER_PRIVATE}}}
    };

<<<NESTED_NAMESPACE_END>>>