///  $URL$
///  $Author$
///  $Revision$
///  $Date$
///
/// \brief This is the struct <<<CLASSNAME>>>.
///
/// \author <<<AUTHOR>>>
/// \Code Autogenerated with MIT License.
///
/// This code is Autogenerated. For manual changes, use the 'USER' tag pairs for preservation of manual additions between round-trips.
///
#pragma once
<<<NOT_FORWARD_DECLARABLE_HEADER_INCLUDES>>>
<<<PACK_BEGIN>>>

/// {{{USER_HEADER_INCLUDES}}}
/// {{{USER_HEADER_INCLUDES}}}

<<<FORWARD_DECLARATIONS>>>
<<<NESTED_NAMESPACE_BEGIN>>>

    /// {{{USER_LOCALS}}}
    /// {{{USER_LOCALS}}}

    <<<CLASS_DOCUMENTATION>>>
    struct <<<CLASSNAME>>>
    {
        <<<STRUCT_EXPAND>>>
    };

<<<NESTED_NAMESPACE_END>>>
<<<PACK_END>>>