///  $URL$
///  $Author$
///  $Revision$
///  $Date$
///
/// \brief This is the header for class <<<CLASSNAME>>>.
///
/// \author <<<AUTHOR>>>
/// \Code Autogenerated with GPL License.
///
/// This code is Autogenerated. For manual changes, use the 'USER' tag pairs for preservation of manual additions between round-trips.
///
//#pragma once

<<<NOT_FORWARD_DECLARABLE_HEADER_INCLUDES>>>

/// {{{USER_HEADER_INCLUDES}}}
/// {{{USER_HEADER_INCLUDES}}}

<<<NESTED_NAMESPACE_BEGIN>>>

    /// {{{USER_LOCALS}}}
    /// {{{USER_LOCALS}}}

    <<<CLASS_DOCUMENTATION>>>
    class <<<DLL_EXPORT>>><<<CLASSNAME>>><<<CLASS_INHERITENCE_HIERARCHY>>>
    {
        ~<<<CLASSNAME>>>()
        {
            /// {{{USER_DESTRUCTOR_<<<CLASSNAME>>>}}}
            /// {{{USER_DESTRUCTOR_<<<CLASSNAME>>>}}}
        }
        <<<CONSTRUCTORS_DECLARE>>>

        <<<PUBLIC_ATTRIBUTES_DECLARE>>>
        <<<PUBLIC_ASSOCIATIONS_DECLARE>>>
        <<<ATTRIBUTES_ASSOCIATIONS_GETTER_SETTER_DECLARE>>>
        <<<PUBLIC_OPERATIONS_DECLARE>>>

        /// {{{USER_PUBLIC}}}
        /// {{{USER_PUBLIC}}}

        <<<PROTECTED_ATTRIBUTES_DECLARE>>>
        <<<PROTECTED_ASSOCIATIONS_DECLARE>>>
        <<<PROTECTED_OPERATIONS_DECLARE>>>

        /// {{{USER_PROTECTED}}}
        /// {{{USER_PROTECTED}}}

        <<<PRIVATE_ATTRIBUTES_DECLARE>>>
        <<<PRIVATE_ASSOCIATIONS_DECLARE>>>
        <<<PRIVATE_OPERATIONS_DECLARE>>>

        /// {{{USER_PRIVATE}}}
        /// {{{USER_PRIVATE}}}
    }

<<<NESTED_NAMESPACE_END>>>