///  $URL$
///  $Author$
///  $Revision$
///  $Date$
///
/// \brief This is the enumeration type <<<CLASSNAME>>>.
///
/// \author <<<AUTHOR>>>
/// \Code Autogenerated with MIT License.
///
/// This code is Autogenerated. For manual changes, use the 'USER' tag pairs for preservation of manual additions between round-trips.
///
//#pragma once

/// {{{USER_HEADER_INCLUDES}}}
/// {{{USER_HEADER_INCLUDES}}}

<<<NESTED_NAMESPACE_BEGIN>>>

    /// {{{USER_LOCALS}}}
    /// {{{USER_LOCALS}}}

    <<<CLASS_DOCUMENTATION>>>
    public enum <<<CLASSNAME>>>
    {
        <<<ENUM_EXPAND>>>
    };

<<<NESTED_NAMESPACE_END>>>