///  $URL$
///  $Author$
///  $Revision$
///  $Date$
///
/// \brief This is the pure virtual interface <<<CLASSNAME>>>.
///
/// \author <<<AUTHOR>>>
/// \Code Autogenerated with MIT License.
///
/// This code is Autogenerated. For manual changes, use the 'USER' tag pairs for preservation of manual additions between round-trips.
///
//#pragma once

<<<NOT_FORWARD_DECLARABLE_HEADER_INCLUDES>>>

/// {{{USER_HEADER_INCLUDES}}}
/// {{{USER_HEADER_INCLUDES}}}

<<<NESTED_NAMESPACE_BEGIN>>>

    /// {{{USER_LOCALS}}}
    /// {{{USER_LOCALS}}}

    <<<CLASS_DOCUMENTATION>>>
    public interface <<<CLASSNAME>>><<<CLASS_INHERITENCE_HIERARCHY>>>
    {
        <<<PUBLIC_OPERATIONS_DECLARE>>>
        /// {{{USER_PUBLIC}}}
        /// {{{USER_PUBLIC}}}
        <<<PROTECTED_OPERATIONS_DECLARE>>>
        /// {{{USER_PROTECTED}}}
        /// {{{USER_PROTECTED}}}
        <<<PRIVATE_OPERATIONS_DECLARE>>>
        /// {{{USER_PRIVATE}}}
        /// {{{USER_PRIVATE}}}
    }

<<<NESTED_NAMESPACE_END>>>