
/**
--------------------------------------------------------------------------------

    MIT License

    Copyright (c) 2015 Eugene Grobbelaar (email : koh.jaen@yahoo.de)

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.


        This file was generated on    : 2017-02-11 01:25:04.
        This file was generated using : win32.
        This file was generated by a machine. Do not modify it by hand.

--------------------------------------------------------------------------------
*/
#pragma once
#include "basetypes.h"
// Memory allocator not used here (as this header forms part of the messages, where it is used)
#if defined(_MSC_VER)
    #define __attribute__(x)
    #pragma pack(push,1)
#elif defined(__GNUC__)
#elif defined(__clang__)
#endif

    /**
    Message Header/Structures used to describe the protocol.
    */

    struct sMsgHeader
    {
        uint16 Preamble                                    __attribute__ ((packed));
        uint16 TypeID                                      __attribute__ ((packed));
        uint32 PayloadSize                                 __attribute__ ((packed));
    };


#if defined(_MSC_VER)
    #pragma pack(pop)
#elif defined(__GNUC__) || defined(__clang__)
    // Nothing required
#endif
